# Site settings
title: 松松的博客
email: xiongsongsong@outlook.com
description: "未来属于我们当中那些仍然愿意弄脏自己双手的少数人。"
baseurl: ""
url: "https://xiongsongsong.github.io"

# Build settings
markdown: kramdown
permalink: pretty
